version: '3'
services:
    # PHP
    phpfpm:
      image: benderalex/phpfpm-yii2
      links:
        - db:db
      volumes:
        - ./app:/var/www/html
        - ./run.sh:/root/run.sh
    phpcli:
      build:
          context: ./phpcli
          dockerfile: php-cli.docker
      volumes:
        - ./app:/var/www/html
        - ./run.sh:/root/run.sh
      working_dir: /var/www/html
      tty: true
    # NGINX
    nginx:
      restart: always
      image: nginx
      ports:
        - "499:80"
      links:
        - phpfpm:phpfpm
      volumes:
        - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/html
        - ./log/nginx:/var/log/nginx
    # MYSQL
    # db:
    #   restart: always
    #   image: mysql
    # #  ports:
    # #   - "3320:3306"
    #   environment:
    #     MYSQL_ROOT_PASSWORD: 111
    #     MYSQL_USER: root
    #     MYSQL_PASSWORD: 111
    #     MYSQL_DATABASE: yii2advanced

    db:
      image: 'mysql:latest'
      volumes:
          - ./database:/var/lib/mysql
      ports:
          - '3306:3306'
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: pass
         MYSQL_DATABASE: database